const translations = {
  es: {
    nav_collabs: "Proyectos",
    nav_collection: "Explorar Obras y Objetos",
    nav_philosophy: "Filosofía",
    nav_artists: "Creadores",
    nav_blog: "Blog",
    nav_events: "Eventos",
    nav_contact: "Conectemos",
    nav_verify: "Verificar",
    verify_title: "Verificación de Autenticidad",
    verify_subtitle: "Ingresá el hash SHA-256 de la obra para verificar su certificación on-chain",
    verify_input_placeholder: "Pegá aquí el hash SHA-256 (64 caracteres hexadecimales)",
    verify_button: "Verificar",
    verify_qr_note: "💡 <strong>Consejo:</strong> Escaneá el QR del certificado para obtener el hash automáticamente",
    verify_error_invalid: "Hash inválido",
    verify_error_invalid_desc: "Por favor ingresá un hash SHA-256 válido (64 caracteres hexadecimales).",
    verify_error_not_found: "No se encontró certificación para este hash",
    verify_error_not_found_desc: "La obra no está registrada en nuestra base de datos de certificaciones.",
    verify_error_database: "Error al verificar",
    verify_error_database_desc: "Hubo un problema al acceder a la base de datos. Intentá nuevamente.",
    hero_subtitle: "Galería de arte inspirado en Bitcoin",
    hero_description: "Descubre obras certificadas on-chain y únete a la comunidad latinoamericana de artistas soberanos.",
    hero_tagline: "Sovereign art for sovereign minds",
    hero_pow: "Proof of Work · Proof of Soul",
    hero_cta: "Explorar Colección",
    hero_scroll: "↓ Explorar",
    collab_label: "Colaboración",
    collab_title: "Colaboración con 21 LAT",
    collab_text: "Diseños exclusivos creados para el proyecto 21 LAT. Arte abstracto aplicado a tarjetas contactless — cada diseño es único e irrepetible.",
    collection_label: "Colección",
    collection_title: "Explorar Obras y Objetos de Diseño",
    collection_text: "Cada obra registra un instante de conciencia irrepetible, una prueba de existencia. Así como Bitcoin inscribe valor en el tiempo, estas piezas inscriben intención, energía y significado.\n\nPinturas y objetos de diseño inspirados en la filosofía de Bitcoin, certificados on-chain como acto de soberanía cultural. La certificación garantiza autenticidad, trazabilidad y permanencia inmutable. La obra habita el mundo físico; su verdad queda anclada en la red.",
    coming: "Próximamente",
    coming_objects: "Objetos · Próximamente",
    badge_available: "Disponible",
    badge_consult: "Consultar",
    objects_label: "Artesanal",
    objects_title: "Hard Art Objects",
    objects_text: "Tiempo convertido en materia. Energía fijada en forma. Piezas únicas en plata, hechas a mano.",
    philosophy_label: "Filosofía",
    philosophy_title: "¿Por qué Hash21?",
    philosophy_text: "Donde el arte se encuentra con la soberanía individual.",
    philosophy_cta: "Explorar Obras y Objetos",
    pillar1_title: "Proof of Work",
    pillar1_text: "Cada obra es trabajo real. Acrílico, textura, capas. No hay ctrl+Z. Cada trazo es irreversible — como cada bloque en la cadena.",
    pillar2_title: "Soberanía",
    pillar2_text: "Arte que no pide permiso. Sin intermediarios que dicten qué crear ni cuánto vale. La obra habla por sí misma.",
    pillar3_title: "21 Millones",
    pillar3_text: "En un mundo de infinita reproducción, lo escaso tiene valor. Cada pieza es única. Finito por diseño — como Bitcoin.",
    artists_label: "Artistas",
    artists_title: "Creadores",
    artists_text: "Hash21 es un refugio para artistas que crean desde la libertad. Creemos que el arte, como Bitcoin, es un acto de soberanía: una decisión consciente de expresar la verdad interior sin pedir permiso, a través del color, la textura, la materia y el tiempo invertido en cada obra. Cada pieza nace del trabajo real y refleja la autenticidad del alma que la crea.\n\nCada creador es guardián de su energía, responsable de su visión y dueño de su proceso. Aquí, el amor por la creación se encuentra con la libertad de existir. Aquí, el valor no se impone: se construye.",
    artists_cta: "Ver Proyectos",
    artist1_role: "Fundadora · Artista",
    artist1_bio: "Arte intuitivo que explora emoción y transformación. Acrílicos, texturas y capas que se construyen como las decisiones que nos forman. Buenos Aires, Argentina.",
    artist1_projects_label: "Proyectos & Experiencia",
    artists_join_cta: "Quiero sumarme como artista →",
    artist1_motto: "Sovereign Art for Sovereign Minds",
    artist1_motto: "Sovereign Art for Sovereign Minds",
    collection_cta: "Conoce a los Creadores",
    collabs_cta: "Leer el Blog",
    contact_label: "Conectemos",
    contact_title: "Conectemos",
    lightning_badge: "₿ Bitcoin only",
    footer: "Hash21 © 2026 — Powered by proof of work ⚡",
    footer_desc: "Sovereign art for sovereign minds",
    footer_nav: "Navegación",
    footer_social: "Redes",
    footer_contact: "Contacto",
    contact_community: "Sumate a la comunidad",
    obra1_code: "Block 0 — #001",
    obra1_name: "The Rabbit",
    obra1_tech: "Acrílico y texturas sobre lienzo",
    obra2_code: "Block 0 — #002",
    obra2_name: "The Hole",
    obra2_tech: "Acrílico y texturas sobre lienzo",
    obra3_code: "Block 0 — #003",
    obra3_name: "Libertad",
    obra3_tech: "Acrílico y texturas sobre lienzo",
    obra4_code: "Block 0 — #004",
    obra4_name: "Horizonte Temporal",
    obra4_tech: "Acrílico y texturas sobre lienzo",
    blog_label: "Blog",
    blog_title: "Noticias & Reflexiones",
    blog_text: "Reflexiones sobre Bitcoin, arte y soberanía. Explorando la intersección entre creatividad y libertad financiera.",
    blog_cta: "Próximos Eventos",
    blog_date1: "15 Feb 2026",
    blog_title1: "Bitcoin y el Arte: Una Revolución Silenciosa",
    blog_excerpt1: "Explorando cómo la filosofía de Bitcoin está transformando el mundo del arte y la creatividad.",
    blog_date2: "12 Feb 2026",
    blog_title2: "Proof of Work en el Lienzo",
    blog_excerpt2: "Cada pincelada es irreversible. Reflexiones sobre el trabajo real en el arte.",
    blog_date3: "08 Feb 2026",
    blog_title3: "La Escasez Digital vs La Escasez Física",
    blog_excerpt3: "¿Qué hace que algo sea verdaderamente único en la era digital?",
    blog_read_more: "Leer más →",
    events_label: "Eventos",
    events_main_title: "Eventos",
    events_text: "Únete a nosotros en exposiciones, charlas y eventos sobre arte y Bitcoin.",
    events_cta: "Conectemos",
    events_upcoming: "Próximos Eventos",
    events_past: "Eventos Pasados",
    event_month1: "MAR",
    event_title1: "Exposición \"Block 0\"",
    event_location1: "Galería Bitcoin Buenos Aires",
    event_desc1: "Primera exposición individual de la serie Block 0. Arte meets filosofía Bitcoin.",
    event_month2: "ABR",
    event_title2: "Charla: \"Arte y Soberanía\"",
    event_location2: "Virtual · Hash21 Studio",
    event_desc2: "Conversación sobre creatividad, libertad financiera y el futuro del arte.",
    past_event_badge: "Evento pasado",
    past_event_month1: "NOV",
    past_event_title1: "La Bitconf Buenos Aires 2025",
    past_event_location1: "Buenos Aires, Argentina",
    past_event_desc1: "Dinámica de arte en vivo en el espacio de 21 LAT. Abstract Lai creando en tiempo real frente al público bitcoiner.",
    newsletter_label: "Comunidad",
    newsletter_title: "Únete a la comunidad",
    newsletter_benefit1: "Novedades de nuevas colecciones",
    newsletter_benefit2: "Acceso anticipado a piezas certificadas",
    newsletter_benefit3: "Newsletter educativo de Bitcoin + Arte",
    newsletter_placeholder: "tu@email.com",
    newsletter_submit: "Suscribirse"
  },
  en: {
    nav_collabs: "Projects",
    nav_collection: "Explore Works & Objects",
    nav_philosophy: "Philosophy",
    nav_artists: "Creators",
    nav_blog: "Blog",
    nav_events: "Events",
    nav_contact: "Let's Connect",
    nav_verify: "Verify",
    verify_title: "Authenticity Verification",
    verify_subtitle: "Enter the SHA-256 hash of the artwork to verify its on-chain certification",
    verify_input_placeholder: "Paste the SHA-256 hash here (64 hexadecimal characters)",
    verify_button: "Verify",
    verify_qr_note: "💡 <strong>Tip:</strong> Scan the certificate QR code to get the hash automatically",
    verify_error_invalid: "Invalid hash",
    verify_error_invalid_desc: "Please enter a valid SHA-256 hash (64 hexadecimal characters).",
    verify_error_not_found: "No certification found for this hash",
    verify_error_not_found_desc: "The artwork is not registered in our certification database.",
    verify_error_database: "Verification error",
    verify_error_database_desc: "There was a problem accessing the database. Please try again.",
    hero_subtitle: "Gallery of art inspired by Bitcoin",
    hero_description: "Discover works certified on-chain and join the Latin American community of sovereign artists.",
    hero_tagline: "Sovereign art for sovereign minds",
    hero_pow: "Proof of Work · Proof of Soul",
    hero_cta: "Explore Collection",
    hero_scroll: "↓ Explore",
    collab_label: "Collaboration",
    collab_title: "Colaboración con 21 LAT",
    collab_text: "Exclusive designs created for the 21 LAT project. Abstract art applied to contactless cards — each design is unique and unrepeatable.",
    collection_label: "Collection",
    collection_title: "Explore Works & Design Objects",
    collection_text: "Each work records an unrepeatable instant of consciousness, a proof of existence. Just as Bitcoin inscribes value over time, these pieces inscribe intention, energy and meaning.\n\nPaintings and design objects inspired by Bitcoin philosophy, certified on-chain as an act of cultural sovereignty. Certification guarantees authenticity, traceability and immutable permanence. The work inhabits the physical world; its truth remains anchored in the network.",
    coming: "Coming soon",
    coming_objects: "Objects · Coming soon",
    badge_available: "Available",
    badge_consult: "Inquire",
    badge_available: "Disponible",
    badge_consult: "Consultar",
    objects_label: "Handcrafted",
    objects_title: "Hard Art Objects",
    objects_text: "Time converted into matter. Energy fixed into form. Unique handcrafted silver pieces.",
    philosophy_label: "Philosophy",
    philosophy_title: "Why Hash21?",
    philosophy_text: "Where art meets individual sovereignty.",
    philosophy_cta: "Explore Works & Objects",
    pillar1_title: "Proof of Work",
    pillar1_text: "Each piece is real work. Acrylic, texture, layers. No ctrl+Z. Every stroke is irreversible — like every block in the chain.",
    pillar2_title: "Sovereignty",
    pillar2_text: "Art that doesn't ask permission. No intermediaries dictating what to create or how much it's worth. The work speaks for itself.",
    pillar3_title: "21 Million",
    pillar3_text: "In a world of infinite reproduction, the scarce has value. Each piece is unique. Finite by design — like Bitcoin.",
    artists_label: "Artists",
    artists_title: "Creators",
    artists_text: "Hash21 is a refuge for artists who create from freedom. We believe that art, like Bitcoin, is an act of sovereignty: a conscious decision to express inner truth without asking permission, through color, texture, matter and the time invested in each work. Every piece is born from real work and reflects the authenticity of the soul that creates it.\n\nEvery creator is guardian of their energy, responsible for their vision and owner of their process. Here, the love of creation meets the freedom to exist. Here, value is not imposed: it is built.",
    artists_cta: "View Projects",
    artist1_role: "Founder · Artist",
    artist1_bio: "Intuitive art exploring emotion and transformation. Acrylics, textures and layers that build like the decisions that shape us. Buenos Aires, Argentina.",
    artist1_projects_label: "Projects & Experience",
    artists_join_cta: "I want to join as an artist →",
    artist1_motto: "Sovereign Art for Sovereign Minds",
    collection_cta: "Meet the Creators",
    collabs_cta: "Read the Blog",
    contact_label: "Connect",
    contact_title: "Let's Connect",
    lightning_badge: "₿ Bitcoin only",
    footer: "Hash21 © 2026 — Powered by proof of work ⚡",
    footer_desc: "Sovereign art for sovereign minds",
    footer_nav: "Navigation",
    footer_social: "Social",
    footer_contact: "Contact",
    contact_community: "Join the community",
    obra1_code: "Block 0 — #001",
    obra1_name: "The Rabbit",
    obra1_tech: "Acrylic and textures on canvas",
    obra2_code: "Block 0 — #002",
    obra2_name: "The Hole",
    obra2_tech: "Acrylic and textures on canvas",
    obra3_code: "Block 0 — #003",
    obra3_name: "Freedom",
    obra3_tech: "Acrylic and textures on canvas",
    obra4_code: "Block 0 — #004",
    obra4_name: "Time Horizon",
    obra4_tech: "Acrylic and textures on canvas",
    blog_label: "Blog",
    blog_title: "News & Reflections",
    blog_text: "Reflections on Bitcoin, art and sovereignty. Exploring the intersection between creativity and financial freedom.",
    blog_cta: "Upcoming Events",
    blog_date1: "Feb 15, 2026",
    blog_title1: "Bitcoin and Art: A Silent Revolution",
    blog_excerpt1: "Exploring how Bitcoin philosophy is transforming the world of art and creativity.",
    blog_date2: "Feb 12, 2026",
    blog_title2: "Proof of Work on Canvas",
    blog_excerpt2: "Every brushstroke is irreversible. Reflections on real work in art.",
    blog_date3: "Feb 08, 2026",
    blog_title3: "Digital Scarcity vs Physical Scarcity",
    blog_excerpt3: "What makes something truly unique in the digital age?",
    blog_read_more: "Read more →",
    events_label: "Events",
    events_main_title: "Events",
    events_text: "Join us at exhibitions, talks and events about art and Bitcoin.",
    events_cta: "Let's Connect",
    events_upcoming: "Upcoming Events",
    events_past: "Past Events",
    event_month1: "MAR",
    event_title1: "\"Block 0\" Exhibition",
    event_location1: "Bitcoin Gallery Buenos Aires",
    event_desc1: "First solo exhibition of the Block 0 series. Physical art meets Bitcoin philosophy.",
    event_month2: "APR",
    event_title2: "Talk: \"Art and Sovereignty\"",
    event_location2: "Virtual · Hash21 Studio",
    event_desc2: "Conversation about creativity, financial freedom and the future of art.",
    past_event_badge: "Past event",
    past_event_month1: "NOV",
    past_event_title1: "La Bitconf Buenos Aires 2025",
    past_event_location1: "Buenos Aires, Argentina",
    past_event_desc1: "Live art dynamic at the 21 LAT booth. Abstract Lai creating in real time in front of the Bitcoin audience.",
    newsletter_label: "Community",
    newsletter_title: "Join the community",
    newsletter_benefit1: "News about new collections",
    newsletter_benefit2: "Early access to certified pieces",
    newsletter_benefit3: "Educational newsletter on Bitcoin + Art",
    newsletter_placeholder: "your@email.com",
    newsletter_submit: "Subscribe"
  }
};

let currentLang = 'es';

function setLang(lang) {
  currentLang = lang;
  const t = translations[lang];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key]) el.textContent = t[key];
  });
  
  // Handle placeholder translations
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key]) el.placeholder = t[key];
  });
  
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
  localStorage.setItem('hash21-lang', lang);
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('hash21-lang');
  if (saved) setLang(saved);
});