const translations = {
  es: {
    nav_collabs: "Proyectos",
    nav_collection: "Explorar Obras y Objetos",
    nav_philosophy: "Filosofía",
    nav_artists: "Creadores",
    nav_blog: "Blog",
    nav_events: "Eventos",
    nav_contact: "Conectemos",
    hero_subtitle: "Galería de arte único inspirado en Bitcoin",
    hero_description: "Descubre obras irrepetibles certificadas on-chain y únete a la comunidad latinoamericana de arte soberano.",
    hero_tagline: "Sovereign art for sovereign minds",
    hero_pow: "Proof of Work · Proof of Soul",
    hero_cta: "Explorar Colección",
    hero_scroll: "↓ Explorar",
    collab_label: "Colaboración",
    collab_title: "Colaboración con 21 LAT",
    collab_text: "Diseños exclusivos creados para el proyecto 21 LAT. Arte abstracto aplicado a tarjetas contactless — cada diseño es único e irrepetible.",
    collection_label: "Obras y objetos",
    collection_title: "Explorar Obras y Objetos",
    collection_text: "Cada obra registra un estado de conciencia irrepetible, así como Bitcoin registra valor en el tiempo. Próximamente certificadas on-chain.",
    coming: "Próximamente",
    coming_objects: "Objetos · Próximamente",
    objects_label: "Artesanal",
    objects_title: "Hard Art Objects",
    objects_text: "Tiempo convertido en materia. Energía fijada en forma. Piezas únicas en plata, hechas a mano.",
    philosophy_label: "Filosofía",
    philosophy_title: "¿Por qué Hash21?",
    philosophy_text: "Donde el arte se encuentra con la soberanía individual.",
    philosophy_cta: "Explorar Obras y Objetos",
    pillar1_title: "Proof of Work",
    pillar1_text: "Cada obra es trabajo real. Acrílico, textura, capas. No hay ctrl+Z. Cada trazo es irreversible — como cada bloque en la cadena.",
    pillar2_title: "Soberanía",
    pillar2_text: "Arte que no pide permiso. Sin intermediarios que dicten qué crear ni cuánto vale. La obra habla por sí misma.",
    pillar3_title: "21 Millones",
    pillar3_text: "En un mundo de infinita reproducción, lo escaso tiene valor. Cada pieza es única. Finito por diseño — como Bitcoin.",
    artists_label: "Artistas",
    artists_title: "Creadores",
    artists_text: "Hash21 es una plataforma curada. Cada artista comparte la visión de soberanía, verdad y trabajo real.",
    artists_cta: "Ver Proyectos",
    artist1_role: "Fundadora · Artista",
    artist1_bio: "Arte intuitivo que explora emoción y transformación. Acrílicos, texturas y capas que se construyen como las decisiones que nos forman. Buenos Aires, Argentina.",
    artist1_motto: "Sovereign Art for Sovereign Minds",
    artist1_motto: "Sovereign Art for Sovereign Minds",
    collection_cta: "Conoce a los Creadores",
    collabs_cta: "Leer el Blog",
    contact_label: "Conectemos",
    contact_title: "Conectemos",
    lightning_badge: "₿ Bitcoin only",
    footer: "Hash21 © 2026 — Powered by proof of work ⚡",
    footer_desc: "Sovereign art for sovereign minds",
    footer_nav: "Navegación",
    footer_social: "Redes",
    footer_contact: "Contacto",
    contact_community: "Sumate a la comunidad",
    obra1_code: "Block 0 — #001",
    obra1_name: "The Rabbit",
    obra1_tech: "Acrílico y texturas sobre lienzo",
    obra2_code: "Block 0 — #002",
    obra2_name: "The Hole",
    obra2_tech: "Acrílico y texturas sobre lienzo",
    obra3_code: "Block 0 — #003",
    obra3_name: "Libertad",
    obra3_tech: "Acrílico y texturas sobre lienzo",
    obra4_code: "Block 0 — #004",
    obra4_name: "Horizonte Temporal",
    obra4_tech: "Acrílico y texturas sobre lienzo",
    blog_label: "Blog",
    blog_title: "Noticias & Reflexiones",
    blog_text: "Reflexiones sobre Bitcoin, arte y soberanía. Explorando la intersección entre creatividad y libertad financiera.",
    blog_cta: "Próximos Eventos",
    blog_date1: "15 Feb 2026",
    blog_title1: "Bitcoin y el Arte: Una Revolución Silenciosa",
    blog_excerpt1: "Explorando cómo la filosofía de Bitcoin está transformando el mundo del arte y la creatividad.",
    blog_date2: "12 Feb 2026",
    blog_title2: "Proof of Work en el Lienzo",
    blog_excerpt2: "Cada pincelada es irreversible. Reflexiones sobre el trabajo real en el arte.",
    blog_date3: "08 Feb 2026",
    blog_title3: "La Escasez Digital vs La Escasez Física",
    blog_excerpt3: "¿Qué hace que algo sea verdaderamente único en la era digital?",
    blog_read_more: "Leer más →",
    events_label: "Eventos",
    events_main_title: "Eventos",
    events_text: "Únete a nosotros en exposiciones, charlas y eventos sobre arte y Bitcoin.",
    events_cta: "Conectemos",
    events_upcoming: "Próximos Eventos",
    events_past: "Eventos Pasados",
    event_month1: "MAR",
    event_title1: "Exposición \"Block 0\"",
    event_location1: "Galería Bitcoin Buenos Aires",
    event_desc1: "Primera exposición individual de la serie Block 0. Arte meets filosofía Bitcoin.",
    event_month2: "ABR",
    event_title2: "Charla: \"Arte y Soberanía\"",
    event_location2: "Virtual · Hash21 Studio",
    event_desc2: "Conversación sobre creatividad, libertad financiera y el futuro del arte.",
    past_event_badge: "Evento pasado",
    past_event_month1: "NOV",
    past_event_title1: "La Bitconf Buenos Aires 2025",
    past_event_location1: "Buenos Aires, Argentina",
    past_event_desc1: "Dinámica de arte en vivo en el espacio de 21 LAT. Abstract Lai creando en tiempo real frente al público bitcoiner.",
    newsletter_label: "Comunidad",
    newsletter_title: "Únete a la comunidad",
    newsletter_benefit1: "Novedades de nuevas colecciones",
    newsletter_benefit2: "Acceso anticipado a piezas certificadas",
    newsletter_benefit3: "Newsletter educativo de Bitcoin + Arte",
    newsletter_placeholder: "tu@email.com",
    newsletter_submit: "Suscribirse"
  },
  en: {
    nav_collabs: "Projects",
    nav_collection: "Explore Works & Objects",
    nav_philosophy: "Philosophy",
    nav_artists: "Creators",
    nav_blog: "Blog",
    nav_events: "Events",
    nav_contact: "Let's Connect",
    hero_subtitle: "Gallery of unique art inspired by Bitcoin",
    hero_description: "Discover unrepeatable works certified on-chain and join the Latin American sovereign art community.",
    hero_tagline: "Sovereign art for sovereign minds",
    hero_pow: "Proof of Work · Proof of Soul",
    hero_cta: "Explore Collection",
    hero_scroll: "↓ Explore",
    collab_label: "Collaboration",
    collab_title: "Colaboración con 21 LAT",
    collab_text: "Exclusive designs created for the 21 LAT project. Abstract art applied to contactless cards — each design is unique and unrepeatable.",
    collection_label: "Works & objects",
    collection_title: "Explore Works & Objects",
    collection_text: "Block 0 Series. Each work records an unrepeatable state of consciousness. Just as Bitcoin records value over time, my work records moments. Soon to be certified on-chain.",
    coming: "Coming soon",
    coming_objects: "Objects · Coming soon",
    objects_label: "Handcrafted",
    objects_title: "Hard Art Objects",
    objects_text: "Time converted into matter. Energy fixed into form. Unique handcrafted silver pieces.",
    philosophy_label: "Philosophy",
    philosophy_title: "Why Hash21?",
    philosophy_text: "Where art meets individual sovereignty.",
    philosophy_cta: "Explore Works & Objects",
    pillar1_title: "Proof of Work",
    pillar1_text: "Each piece is real work. Acrylic, texture, layers. No ctrl+Z. Every stroke is irreversible — like every block in the chain.",
    pillar2_title: "Sovereignty",
    pillar2_text: "Art that doesn't ask permission. No intermediaries dictating what to create or how much it's worth. The work speaks for itself.",
    pillar3_title: "21 Million",
    pillar3_text: "In a world of infinite reproduction, the scarce has value. Each piece is unique. Finite by design — like Bitcoin.",
    artists_label: "Artists",
    artists_title: "Creators",
    artists_text: "Hash21 is a curated platform. Every artist shares the vision of sovereignty, truth, and real work.",
    artists_cta: "View Projects",
    artist1_role: "Founder · Artist",
    artist1_bio: "Intuitive art exploring emotion and transformation. Acrylics, textures and layers that build like the decisions that shape us. Buenos Aires, Argentina.",
    artist1_motto: "Sovereign Art for Sovereign Minds",
    collection_cta: "Meet the Creators",
    collabs_cta: "Read the Blog",
    contact_label: "Connect",
    contact_title: "Let's Connect",
    lightning_badge: "₿ Bitcoin only",
    footer: "Hash21 © 2026 — Powered by proof of work ⚡",
    footer_desc: "Sovereign art for sovereign minds",
    footer_nav: "Navigation",
    footer_social: "Social",
    footer_contact: "Contact",
    contact_community: "Join the community",
    obra1_code: "Block 0 — #001",
    obra1_name: "The Rabbit",
    obra1_tech: "Acrylic and textures on canvas",
    obra2_code: "Block 0 — #002",
    obra2_name: "The Hole",
    obra2_tech: "Acrylic and textures on canvas",
    obra3_code: "Block 0 — #003",
    obra3_name: "Freedom",
    obra3_tech: "Acrylic and textures on canvas",
    obra4_code: "Block 0 — #004",
    obra4_name: "Time Horizon",
    obra4_tech: "Acrylic and textures on canvas",
    blog_label: "Blog",
    blog_title: "News & Reflections",
    blog_text: "Reflections on Bitcoin, art and sovereignty. Exploring the intersection between creativity and financial freedom.",
    blog_cta: "Upcoming Events",
    blog_date1: "Feb 15, 2026",
    blog_title1: "Bitcoin and Art: A Silent Revolution",
    blog_excerpt1: "Exploring how Bitcoin philosophy is transforming the world of art and creativity.",
    blog_date2: "Feb 12, 2026",
    blog_title2: "Proof of Work on Canvas",
    blog_excerpt2: "Every brushstroke is irreversible. Reflections on real work in art.",
    blog_date3: "Feb 08, 2026",
    blog_title3: "Digital Scarcity vs Physical Scarcity",
    blog_excerpt3: "What makes something truly unique in the digital age?",
    blog_read_more: "Read more →",
    events_label: "Events",
    events_main_title: "Events",
    events_text: "Join us at exhibitions, talks and events about art and Bitcoin.",
    events_cta: "Let's Connect",
    events_upcoming: "Upcoming Events",
    events_past: "Past Events",
    event_month1: "MAR",
    event_title1: "\"Block 0\" Exhibition",
    event_location1: "Bitcoin Gallery Buenos Aires",
    event_desc1: "First solo exhibition of the Block 0 series. Physical art meets Bitcoin philosophy.",
    event_month2: "APR",
    event_title2: "Talk: \"Art and Sovereignty\"",
    event_location2: "Virtual · Hash21 Studio",
    event_desc2: "Conversation about creativity, financial freedom and the future of art.",
    past_event_badge: "Past event",
    past_event_month1: "NOV",
    past_event_title1: "La Bitconf Buenos Aires 2025",
    past_event_location1: "Buenos Aires, Argentina",
    past_event_desc1: "Live art dynamic at the 21 LAT booth. Abstract Lai creating in real time in front of the Bitcoin audience.",
    newsletter_label: "Community",
    newsletter_title: "Join the community",
    newsletter_benefit1: "News about new collections",
    newsletter_benefit2: "Early access to certified pieces",
    newsletter_benefit3: "Educational newsletter on Bitcoin + Art",
    newsletter_placeholder: "your@email.com",
    newsletter_submit: "Subscribe"
  }
};

let currentLang = 'es';

function setLang(lang) {
  currentLang = lang;
  const t = translations[lang];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key]) el.textContent = t[key];
  });
  
  // Handle placeholder translations
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key]) el.placeholder = t[key];
  });
  
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
  localStorage.setItem('hash21-lang', lang);
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('hash21-lang');
  if (saved) setLang(saved);
});